Format entire schema extractor to be able to handle exceptions and support the new OAI structured output
tensorlakeai/indexify-extractors pull request #222
Opened 2024-08-08 22:45 UTC by rishiraj

2024-08-09 16:03 UTC, diptanu requested changes

2024-08-09 16:03 UTC, diptanu commented on text/schema/schema_extractor.py
> +                        response = self._process_image(temp_image_file.name, model_name, key, prompt, query, response_format)
Remove these tmp files, process the bytes directly

2024-08-09 16:03 UTC, diptanu commented on text/schema/schema_extractor.py
> +        key = params.api_key
Assign the key if the key is set

2024-08-12 12:01 UTC, rishiraj commented
@diptanu temp file issue is solved & I've moved key loading to a _get_client function that takes from environment or else manually if overwritten.

2024-08-12 12:01 UTC, merged